import type { Metadata } from "next";
import { HTRakikBold, ReadexProMedium, ReadexProRegular } from "./fonts";
import classNames from "classnames";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <link href="favicon.svg" rel="icon" media="(prefers-color-scheme: light)"/> */}
      </head>
      <body
        className={classNames(
          ReadexProRegular.variable,
          ReadexProMedium.variable,
          HTRakikBold.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
